name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Publish Kotlin Multiplatform metadata
        run: ./gradlew publishKotlinMultiplatformPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish iOS targets
        if: matrix.os == 'macos-latest'
        run: |
          ./gradlew \
            publishIosX64PublicationToGitHubPackagesRepository \
            publishIosArm64PublicationToGitHubPackagesRepository \
            publishIosSimulatorArm64PublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
