name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Publish all publications
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
